image: registry.getech.cn/getech/ci-java:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2  
  VERSION_BASE: "1.0."
  CI_IMAGE_TAG: $VERSION_BASE$CI_PIPELINE_IID
  CI_REGISTRY_IMAGE: $CI_REGISTRY/iot/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
  

stages:
  - build
  - package
  
npm-build:
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build 
  cache:
    paths:
      - node_modules/    
  artifacts:
    name: $CI_PROJECT_NAME
    expire_in: 1 day
    paths:
      - interface/*


    
Docker-Build:
  stage: package
  before_script:
    - docker login -u $GETECH_CI_REGISTRY_USER -p $GETECH_CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export CI_REGIST2RY_IMAGE=`echo "$CI_REGISTRY_IMAGE" | tr '[:upper:]' '[:lower:]'`
    - echo $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
    - CI_PROJECT_BASE=`echo $CI_PROJECT_URL | cut -d'/' -f3`
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest  


